{% set name = "jbig" %}
{% set version = "2.1" %}
{% set sha256 = "de7106b6bfaf495d6865c7dd7ac6ca1381bd12e0d81405ea81e7f2167263d932" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://www.cl.cam.ac.uk/~mgk25/jbigkit/download/jbigkit-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    # Remove -Wno-unused-result (for compatibility with old gcc),
    # and add -fPIC (to allow shared libraries to use this build).
    - Makefile.patch

build:
  number: 0

requirements:
  build:
    - toolchain
    - m2-bash # [win]
    - m2-autoconf # [win]
    - m2-autoconf-wrapper # [win]
    - m2-curl # [win]
    - m2-findutils # [win]
    - m2-grep # [win]
    - m2-libtool # [win]
    - m2-make # [win]
    - m2-which # [win]
    - m2w64-binutils # [win]
    - m2w64-pcre # [win]
    - m2w64-gcc # [win]
    - m2w64-toolchain # [win]
    - m2w64-tools-git # [win]
  run
    - m2w64-gcc-libs # [win]

test:
  commands:
    - test -f $PREFIX/lib/libjbig.a

about:
  home: https://www.cl.cam.ac.uk/~mgk25/jbigkit
  license: GPL-2.0
  license_family: GPL
  license_file: COPYING
  summary: 'Implementation of the JBIG1 data compression standard'

  description: |
    JBIG-KIT provides a portable library of compression and decompression
    functions with a documented interface that you can include very easily
    into your image or document processing software.
  doc_url: https://www.cl.cam.ac.uk/~mgk25/jbigkit/
  dev_url: https://www.cl.cam.ac.uk/~mgk25/git/jbigkit/

extra:
  recipe-maintainers:
    - nehaljwani
